In [8]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-23
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-23
    @Title: numPy Programs - Create a 3 by 3 diagonal matrix
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-23\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-23\n    @Title: numPy Programs - Create a 3 by 3 diagonal matrix\n'

In [9]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('diagonal_matrix')

In [10]:
def create_diagonal_matrix():
    """
    Description:
        Creates a 3 by 3 diagonal matrix.
    Parameter:
        None
    Return:
        3 by 3 diagonal matrix.
    """
    diagonal_matrix = np.eye(3)
    return diagonal_matrix

In [11]:
def main():
    logger.info(f"3 x 3 diagonal matrix is: \n {create_diagonal_matrix()}")

In [12]:
if __name__ == "__main__":
    main()

2022-03-24 10:00:11,244:INFO:diagonal_matrix:3 x 3 diagonal matrix is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2022-03-24 10:00:11,244:INFO:diagonal_matrix:3 x 3 diagonal matrix is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
