In [1]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-23
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-23
    @Title: numPy Programs - Create a triangle matrix
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-23\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-23\n    @Title: numPy Programs - Create a triangle matrix\n'

In [2]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('triangle_matrix')

In [3]:
def create_triangle_matrix():
    triangle_matrix = np.tri(4, 3, k=-1)
    return triangle_matrix

In [4]:
def main():
    logger.info(f"Triangle matrix is: \n {create_triangle_matrix()}")

In [5]:
if __name__ == "__main__":
    main()

2022-03-23 20:27:19,166:INFO:triangle_matrix:Triangle matrix is: [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
