In [11]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-23
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-23
    @Title: numPy Programs - Concatenate two 2dimensional arrays
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-23\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-23\n    @Title: numPy Programs - Concatenate two 2dimensional arrays\n'

In [12]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('concatenate_2d_arrays')

In [13]:
def concatenate_2darrays(given_array1, given_array2):
    """
    Description :
        Concatenates two given 2-Dimensional arrays.
    Parameters :
        given_array1: Given array which is to be concatenated with other given array.
        given_array2: Given other array which is to be concatenated with first array.
    Return :
        Concatenated array of the two given 2D arrays.
    """
    # axis=1 for column wise concatenation, axis=0 can be used for row wise concatenation.
    return np.concatenate((given_array1, given_array2), axis=1)

In [14]:
def main():
    sample_array = np.array([[0, 1, 2], [5, 6, 7]])
    sample_array2 = np.array([[0, 2, 4], [3, 7, 9]])
    logger.info(f"Given Array 1: {sample_array}")
    logger.info(f"Given Array 2: {sample_array2}")
    logger.info(f"Concantenation of two given arrays: {concatenate_2darrays(sample_array, sample_array2)}")

In [15]:
if __name__ == "__main__":
    main()

Given Array 1: [[0 1 2]
 [5 6 7]]
Given Array 2: [[0 2 4]
 [3 7 9]]
Concantenation of two given arrays: [[0 1 2 0 2 4]
 [5 6 7 3 7 9]]
