In [4]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-23
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-23
    @Title: numPy Programs - Create Immutable Array
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-23\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-23\n    @Title: numPy Programs - Create Immutable Array\n'

In [5]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('immutable_array')

In [6]:
def immutable_array(given_array):
    """
    Description:
        Makes given array immutable.
    Parameter:
        given_array: Given array to be made immutable.
    Return:
        Immutable array.
    """
    # Writable Flag of NumPy set to False.
    given_array.flags.writeable = False
    return given_array

In [7]:
def main():
    try :
        identity_matrix = np.eye(5)
        logger.info(f"5 by 5 Identity Matrix: {identity_matrix}")
        identity_matrix[2] = 1
        logger.info(f"Matrix after changing 3rd value to 1: {identity_matrix}")
        logger.info(f"Changing the value in Matrix after setting it to read only: {immutable_array(identity_matrix)}")
        logger.info(f"Trying to change the value of the second value to 3:")
        identity_matrix[2] = 3
    except Exception as e:
        print(f"{e} is raised.")

In [8]:
if __name__ == "__main__":
    main()

2022-03-23 23:53:10,930:INFO:immutable_array:5 by 5 Identity Matrix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2022-03-23 23:53:10,930:INFO:immutable_array:5 by 5 Identity Matrix: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2022-03-23 23:53:10,932:INFO:immutable_array:Matrix after changing 3rd value to 1: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2022-03-23 23:53:10,932:INFO:immutable_array:Matrix after changing 3rd value to 1: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2022-03-23 23:53:10,933:INFO:immutable_array:Changing the value in Matrix after setting it to read only: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2022-03-23 23:53:10,933:INFO:immutable_array:Changing the value in Matrix after setting it to read only: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0.

assignment destination is read-only is raised.
