In [1]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-23
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-23
    @Title: numPy Programs - Multiple Array by 3
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-23\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-23\n    @Title: numPy Programs - Multiple Array by 3\n'

In [2]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('multiply_3')

In [3]:
def multiply_by_3(given_array):
    """
    Description:
        Multiples each element of given array by 3.
    Parameter:
        given_array: Given array in which each element is multiplied by 3.
    Return:
        Given array with elements multipled by 3.
    """
    return given_array * 3

In [4]:
def main():
    sample_array = np.arange(12).reshape(3,4)
    logger.info(f"Given array:")
    logger.info(f"{sample_array}")
    logger.info(f"Array elements multiplied by 3:")
    logger.info(f"{multiply_by_3(sample_array)}")

In [5]:
if __name__ == "__main__":
    main()

2022-03-24 00:00:26,640:INFO:multiply_3:Given array:
2022-03-24 00:00:26,642:INFO:multiply_3:[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2022-03-24 00:00:26,643:INFO:multiply_3:Array elements multiplied by 3:
2022-03-24 00:00:26,644:INFO:multiply_3:[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
