In [1]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-22
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-22
    @Title: numPy Programs - Add Null Values to Ones Matrix
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-22\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-22\n    @Title: numPy Programs - Add Null Values to Ones Matrix\n'

In [2]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('add_border_1_to_matrix')

In [3]:
def add_0_to_ones_matrix(ones_matrix):
    """
    Description:
        Adds 0 inside 5 by 5 matrix containing all 1 values leaving only border with 1 values.
    Parameter:
        ones_matrix: 5 by 5 matrix containing all 1 values.
    Return:
        Resultant matrix with 1 on border and 0 on the inside of the matrix.
    """
    ones_matrix[1:4,1:4] = 0
    return ones_matrix

In [4]:
def main():
    # Creates 5 by 5 ones matrix using numPy ones method.
    ones_matrix = np.ones((5,5))
    logger.info(f"Given 5-dimensional Matrix:")
    logger.info(f"{ones_matrix}")
    logger.info(f"Matrix after adding 0 inside in the array leaving border with 1:")
    logger.info(f"{add_0_to_ones_matrix(ones_matrix)}")

In [5]:
if __name__ == "__main__":
    main()

2022-03-22 19:08:02,679:INFO:add_border_1_to_matrix:Given 5-dimensional Matrix:
2022-03-22 19:08:02,681:INFO:add_border_1_to_matrix:[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2022-03-22 19:08:02,682:INFO:add_border_1_to_matrix:Matrix after adding 0 inside in the array leaving border with 1:
2022-03-22 19:08:02,683:INFO:add_border_1_to_matrix:[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
