In [1]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-22
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-22
    @Title: numPy Programs - Add Border to Ones Matrix
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-22\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-22\n    @Title: numPy Programs - Add Border to Ones Matrix\n'

In [2]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('add_border_to_ones_matrix')

In [3]:
def add_0_border(given_matrix):
    """
    Description:
        Adds 0 border to given matrix of any size.
    Parameter:
        given_matrix: Given matrix of any size in which border 0 is to be added.
    Return:
        Resultant matrix with 0 on border and same remaining values in the given matrix.
    """
    bordered_matrix = np.pad(given_matrix, pad_width=1, mode='constant', constant_values=0)
    return bordered_matrix

In [4]:
def main():
    sample_matrix = np.ones((3,3))
    logger.info(f"Given Matrix:")
    logger.info(f"{sample_matrix}")
    logger.info(f"Matrix after adding 0 on the border of one's Matrix:")
    logger.info(f"({add_0_border(sample_matrix)}")

In [5]:
if __name__ == "__main__":
    main()

2022-03-22 19:21:39,627:INFO:add_border_to_ones_matrix:Given Matrix:
2022-03-22 19:21:39,629:INFO:add_border_to_ones_matrix:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2022-03-22 19:21:39,630:INFO:add_border_to_ones_matrix:Matrix after adding 0 on the border of one's Matrix:
2022-03-22 19:21:39,632:INFO:add_border_to_ones_matrix:([[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
