In [1]:
"""
    @Author: Mayank Anand
    @Date: 2022-03-22
    @Last Modified by: Mayank Anand
    @Last Modified time: 2022-03-22
    @Title: numPy Programs - Checkboard Matrix
"""

'\n    @Author: Mayank Anand\n    @Date: 2022-03-22\n    @Last Modified by: Mayank Anand\n    @Last Modified time: 2022-03-22\n    @Title: numPy Programs - Checkboard Matrix\n'

In [2]:
# Importing required libraries
import numpy as np
import logger

logger = logger.logging_init('checkboard_matrix')

In [3]:
def checkboard_matrix(given_matrix):
    """
    Description:
        Adds 0 border to given matrix of any size.
    Parameter:
        given_matrix: Given matrix of any size in which border 0 is to be added.
    Return:
        Resultant matrix with 0 on border and same remaining values in the given matrix.
    """
    given_matrix[1::2, ::2] = 1
    given_matrix[::2, 1::2] = 1
    return given_matrix


In [4]:
def main():
    null_matrix = np.zeros((8,8))
    logger.info(f"Matrix after adding Checkboard Pattern:")
    logger.info(f"{checkboard_matrix(null_matrix)}")

In [5]:
if __name__ == "__main__":
    main()

2022-03-22 19:25:31,353:INFO:checkboard_matrix:Matrix after adding Checkboard Pattern:
2022-03-22 19:25:31,355:INFO:checkboard_matrix:[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
